# Generated by Django 5.0 on 2024-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="website_url",
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
