# Generated by Django 5.0 on 2024-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurantschedule_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='allow_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
