# Generated by Django 5.0 on 2024-01-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_restaurantcategory_delete_restauranttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurantcategory",
            ),
        ),
    ]
