# Generated by Django 5.0 on 2024-01-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0011_restaurant_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="category",
        ),
    ]
