# Generated by Django 5.0 on 2024-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0012_remove_restaurant_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(to="restaurants.restaurantcategory"),
        ),
    ]
