# Generated by Django 5.0 on 2024-01-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_restaurant_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='categories',
            field=models.ManyToManyField(to='restaurants.fooditemcategory'),
        ),
    ]
