# Generated by Django 5.0 on 2024-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_restaurantschedule_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantschedule',
            name='status',
            field=models.CharField(choices=[('OPENING', 'Opening'), ('CLOSED', 'Closed')], default='Opening', max_length=20),
        ),
    ]
