# Generated by Django 5.0 on 2024-03-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0020_alter_singleorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="categories",
            field=models.ManyToManyField(null=True, to="restaurants.fooditemcategory"),
        ),
    ]
