# Generated by Django 5.0 on 2024-03-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0021_alter_fooditem_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="categories",
            field=models.ManyToManyField(to="restaurants.fooditemcategory"),
        ),
    ]
