# Generated by Django 5.0 on 2024-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0022_alter_fooditem_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients",
            field=models.ManyToManyField(to="restaurants.ingredient"),
        ),
    ]
