# Generated by Django 5.0 on 2024-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0023_ingredient_fooditem_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="type",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Group", "Group"),
                    ("Catering", "Catering"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
