# Generated by Django 5.0 on 2024-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0024_restaurant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="type",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Group", "Group"),
                    ("Catering", "Catering"),
                ],
                default="Single",
                max_length=200,
            ),
        ),
    ]
