# Generated by Django 5.0 on 2024-04-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0025_alter_restaurant_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="type",
        ),
        migrations.CreateModel(
            name="RestaurantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Group", "Group"),
                            ("Catering", "Catering"),
                        ],
                        default="Single",
                        max_length=200,
                    ),
                ),
                ("people_from_range", models.IntegerField()),
                ("people_to_range", models.IntegerField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
        ),
    ]
