# Generated by Django 5.0 on 2024-04-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0026_remove_restaurant_type_restauranttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restauranttype",
            name="people_from_range",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="restauranttype",
            name="people_to_range",
            field=models.IntegerField(null=True),
        ),
    ]
