# Generated by Django 5.0 on 2024-04-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0027_alter_restauranttype_people_from_range_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restauranttype",
            name="people_from_range",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restauranttype",
            name="people_to_range",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
