# Generated by Django 5.0 on 2024-04-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0028_alter_restauranttype_people_from_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouporder",
            name="company",
        ),
    ]
