# Generated by Django 5.0 on 2024-04-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0014_foodhistory_is_menu_selected"),
        (
            "restaurants",
            "0030_grouporder_delivered_date_grouporder_delivered_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="grouporder",
            name="teammember",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.teammember",
            ),
        ),
        migrations.AddField(
            model_name="grouporder",
            name="type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                ],
                default="Breakfast",
                max_length=200,
            ),
        ),
    ]
