# Generated by Django 5.0 on 2024-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0033_alter_grouporder_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouporder",
            name="delivered_time",
            field=models.TimeField(null=True),
        ),
    ]
