# Generated by Django 5.0 on 2024-04-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0035_cateringorder_cateringorderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cateringorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.cateringorder",
            ),
        ),
    ]
