# Generated by Django 5.0 on 2024-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0038_remove_fooditem_payment_redirect_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cateringorder",
            name="payment_redirect_url",
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="grouporder",
            name="payment_redirect_url",
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
