# Generated by Django 5.0 on 2024-04-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0041_cateringorder_restaurant_grouporder_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cateringorder",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="grouporder",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="singleorder",
            name="restaurant",
        ),
        migrations.AddField(
            model_name="cateringorderitem",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="grouporderitem",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="singleorderitem",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
        ),
    ]
