# Generated by Django 5.0 on 2024-04-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0042_remove_cateringorder_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouporder",
            name="allowed_budget",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
