# Generated by Django 5.0 on 2024-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_team_company_team_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamrule",
            name="default_rule",
            field=models.BooleanField(default=True),
        ),
    ]
