# Generated by Django 5.0 on 2024-04-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_teamrule_default_rule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamrule",
            name="name",
        ),
    ]
