# Generated by Django 5.0 on 2024-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_remove_teamrule_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamrule",
            name="budget_per_order",
        ),
        migrations.RemoveField(
            model_name="teamrule",
            name="default_rule",
        ),
        migrations.RemoveField(
            model_name="teamrule",
            name="order_per_day",
        ),
        migrations.AddField(
            model_name="teamrule",
            name="allow_breakfast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="allow_dinner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="allow_lunch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="breakfast_budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="dinner_budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="lunch_budget",
            field=models.IntegerField(default=0),
        ),
    ]
