# Generated by Django 5.0 on 2024-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_remove_team_budget_remove_teammember_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamrule",
            name="breakfast_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="dinner_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="teamrule",
            name="lunch_time",
            field=models.TimeField(null=True),
        ),
    ]
