# Generated by Django 5.0 on 2024-04-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_teamrule_breakfast_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodhistory",
            name="team_rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.teamrule",
            ),
        ),
    ]
