# Generated by Django 5.0 on 2024-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_foodhistory_team_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodhistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Dinner", "Dinner"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
