# Generated by Django 5.0 on 2024-04-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_remove_foodhistory_team_remove_foodhistory_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodhistory",
            name="teammember",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.teammember",
            ),
        ),
    ]
