# Generated by Django 5.0 on 2024-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_alter_foodhistory_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodhistory",
            name="is_menu_selected",
            field=models.BooleanField(default=False),
        ),
    ]
